### ISSUE TITLE
When compiling, Error and warning occurs.

### ISSUE THREAD

**Issue by ansee7221** [espressif/esp32-iotivity#6]
When compiling, the following error and warning occurs.

root@work:/home/project/esp32-iotivity# make app
~~
`CC build/coap/libcoap/src/option.o
/home/project/esp32-iotivity/esp-idf/components/coap/libcoap/src/option.c: In function 'coap_opt_length':
/home/project/esp32-iotivity/esp-idf/components/coap/libcoap/src/option.c:260:5: warning: this statement may fall through [-Wimplicit-fallthrough=]
     ++opt;
     ^~~~~

~~
skip 
~~

CXX build/cxx/cxx_exception_stubs.o
In file included from /root/esp/xtensa-esp32-elf/xtensa-esp32-elf/sys-include/stdlib.h:18,
                 from /root/esp/xtensa-esp32-elf/xtensa-esp32-elf/include/c++/8.2.0/cstdlib:75,
                 from /home/kd-one/project/smart_grid/esp32-iotivity/esp-idf/components/cxx/./cxx_exception_stubs.cpp:1:
/home/project/esp32-iotivity/esp-idf/components/newlib/include/sys/reent.h:166:8: error: '_VOID' does not name a type
 extern _VOID   _EXFUN(__sinit,(struct _reent *));
        ^~~~~
/home/project/esp32-iotivity/esp-idf/components/newlib/include/sys/reent.h:193:3: error: '_PTR' does not name a type
   _PTR _cookie; /* cookie passed to io functions */
   ^~~~

~~
skip 
~~`

**Comment by cima** [comment]
Can you please elaborate on how this issue had been solved? I have run into the same issue when combining esp-idf v3.3, Toolchain https://dl.espressif.com/dl/xtensa-esp32-elf-gcc8_2_0-esp32-2019r1-win32.zip while enabling C++17 and Exceptions.

Issues like https://github.com/aws/amazon-freertos/issues/810 suggests downgrading compiler, but that doesn't allow me to use C++17. I found out that there are two kinds of _ansi.h files. One in the toolchain that apparently takes precedence and the other in esp-idf/components/newlib/include that conatains the desired macros.

Did you somehow manage to use the later include? Suggestions to enable static linkage in freertos (https://github.com/aws/amazon-freertos/issues/751) didn't solved my issue.
